In [1]:
import numpy as np 
import pandas as pd

In [2]:
df=pd.read_csv(r'D:\iti_project\house_prices.csv')  # Load your dataset here
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [3]:
df.isnull().sum()  # Check for missing values

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [4]:
df.describe()  # Get summary statistics for numerical columns

               Index  Price (in rupees)  Dimensions  Plot Area
count  187531.000000       1.698660e+05         0.0        0.0
mean    93765.000000       7.583772e+03         NaN        NaN
std     54135.681003       2.724171e+04         NaN        NaN
min         0.000000       0.000000e+00         NaN        NaN
25%     46882.500000       4.297000e+03         NaN        NaN
50%     93765.000000       6.034000e+03         NaN        NaN
75%    140647.500000       9.450000e+03         NaN        NaN
max    187530.000000       6.700000e+06         NaN        NaN

In [5]:
print(df.columns.tolist())
columns_to_drop = ['Society', 'Dimensions', 'Plot Area', 'Index', 'Title', 'Description']
print([c in df.columns for c in columns_to_drop])
df.drop(columns=columns_to_drop, inplace=True)
print(df.columns.tolist())

['Index', 'Title', 'Description', 'Amount(in rupees)', 'Price (in rupees)', 'location', 'Carpet Area', 'Status', 'Floor', 'Transaction', 'Furnishing', 'facing', 'overlooking', 'Society', 'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area', 'Dimensions', 'Plot Area']
[True, True, True, True, True, True]
['Amount(in rupees)', 'Price (in rupees)', 'location', 'Carpet Area', 'Status', 'Floor', 'Transaction', 'Furnishing', 'facing', 'overlooking', 'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area']

In [6]:
df.info()  # Get information about the DataFrame, including data types and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Amount(in rupees)  187531 non-null  str
 1   Price (in rupees)  169866 non-null  float64
 2   location           187531 non-null  str
 3   Carpet Area        106858 non-null  str
 4   Status             186916 non-null  str
 5   Floor              180454 non-null  str
 6   Transaction        187448 non-null  str
 7   Furnishing         184634 non-null  str
 8   facing             117298 non-null  str
 9   overlooking        106095 non-null  str
 10  Bathroom           186703 non-null  str
 11  Balcony            138596 non-null  str
 12  Car Parking        84174 non-null   str
 13  Ownership          122014 non-null  str
 14  Super Area         79846 non-null   str
dtypes: float64(1), str(14)
memory usage: 21.5 MB

In [7]:
df['Amount(in rupees)'].isnull().sum()  # Check for missing values in the 'Amount(in rupees)' column
def parse_amount(x):
    if not isinstance(x, str):
        return None
    
    x = x.strip().lower()
    try:
        if "lac" in x:
            return float(x.replace("lac", "").strip()) * 1e5
        if "cr" in x:
            return float(x.replace("cr", "").strip()) * 1e7
        return float(x.replace(",", ""))
    except ValueError:
        return None
df["price_clean"] = df["Amount(in rupees)"].apply(parse_amount)
df.dropna(subset=["price_clean"], inplace=True)
print(df[["Amount(in rupees)", "price_clean"]].head(10))

  Amount(in rupees)  price_clean
0           42 Lac     4200000.0
1           98 Lac     9800000.0
2          1.40 Cr    14000000.0
3           25 Lac     2500000.0
4          1.60 Cr    16000000.0
5           45 Lac     4500000.0
6         16.5 Lac     1650000.0
7           60 Lac     6000000.0
8           60 Lac     6000000.0
9          1.60 Cr    16000000.0

In [8]:
df.info()  # Get information about the DataFrame, including data types and non-null counts

<class 'pandas.DataFrame'>
Index: 177847 entries, 0 to 187530
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Amount(in rupees)  177847 non-null  str
 1   Price (in rupees)  169866 non-null  float64
 2   location           177847 non-null  str
 3   Carpet Area        101522 non-null  str
 4   Status             177252 non-null  str
 5   Floor              170898 non-null  str
 6   Transaction        177780 non-null  str
 7   Furnishing         175780 non-null  str
 8   facing             112111 non-null  str
 9   overlooking        102022 non-null  str
 10  Bathroom           177087 non-null  str
 11  Balcony            130688 non-null  str
 12  Car Parking        81935 non-null   str
 13  Ownership          115922 non-null  str
 14  Super Area         76235 non-null   str
 15  price_clean        177847 non-null  float64
dtypes: float64(2), str(14)
memory usage: 23.1 MB

In [9]:
df["Price (in rupees)"].isnull().sum()  # Check for missing values in the 'Price (in rupees)' column
df["Price (in rupees)"].value_counts()  # Get the count of unique values in the 'Price (in rupees)' column
df["Price (in rupees)"].mean()  # Calculate the mean of the 'Price (in rupees)' column
df["Price (in rupees)"]= df["Price (in rupees)"].fillna(df["Price (in rupees)"].mean())  # Fill missing values with the mean
df["Price (in rupees)"]

0          6000.000000
1         13799.000000
2         17500.000000
3          7583.771885
4         18824.000000
              ...
187526     3225.000000
187527     3274.000000
187528     4343.000000
187529     4231.000000
187530     6162.000000
Name: Price (in rupees), Length: 177847, dtype: float64

In [10]:
df.info()  # Get information about the DataFrame, including data types and non-null counts

<class 'pandas.DataFrame'>
Index: 177847 entries, 0 to 187530
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Amount(in rupees)  177847 non-null  str
 1   Price (in rupees)  177847 non-null  float64
 2   location           177847 non-null  str
 3   Carpet Area        101522 non-null  str
 4   Status             177252 non-null  str
 5   Floor              170898 non-null  str
 6   Transaction        177780 non-null  str
 7   Furnishing         175780 non-null  str
 8   facing             112111 non-null  str
 9   overlooking        102022 non-null  str
 10  Bathroom           177087 non-null  str
 11  Balcony            130688 non-null  str
 12  Car Parking        81935 non-null   str
 13  Ownership          115922 non-null  str
 14  Super Area         76235 non-null   str
 15  price_clean        177847 non-null  float64
dtypes: float64(2), str(14)
memory usage: 23.1 MB

In [11]:
"""Car Parking
Balcony
Bathroom
Floor
Carpet Area
Super Area"""
# to maping to numerical values

'Car Parking\nBalcony\nBathroom\nFloor\nCarpet Area\nSuper Area'

In [12]:
df["Super Area"].value_counts() # Get the count of unique values in the 'Super Area' column

Super Area
1100 sqft    2567
1332 sqft    2110
1500 sqft    1998
500 sqft     1651
1000 sqft    1294
             ...
147 sqyrd       1
217 sqyrd       1
2066 sqft       1
406 sqft        1
2332 sqft       1
Name: count, Length: 2897, dtype: int64

In [13]:
import numpy as np
def parse_area(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x).lower().strip()
    parts = x.split()
    
    if len(parts) >= 1:
        try:
            val = float(parts[0]) 
        except ValueError:
            return np.nan
        
        unit = parts[1] if len(parts) > 1 else 'sqft'
        
        if 'sqm' in unit:
            return val * 10.764 
        elif 'sqyrd' in unit or 'syrd' in unit:
            return val * 9.0    
        else:
            return val          
    return np.nan
df['carpet_temp'] = df['Carpet Area'].apply(parse_area)
df['super_temp'] = df['Super Area'].apply(parse_area)
df['carpet_area_sqft'] = df['carpet_temp'].fillna(df['super_temp'])
df.drop(columns=['Carpet Area', 'Super Area', 'carpet_temp', 'super_temp'], inplace=True)
print(df['carpet_area_sqft'].isna().sum(), "Nulls remaining in carpet_area_sqft")

125 Nulls remaining in carpet_area_sqft

In [14]:
import re
def extract_number(x):
    if pd.isna(x):
        return np.nan
    
    # Extract the first integer found in the string
    match = re.search(r'\d+', str(x))
    if match:
        return float(match.group())    
    return np.nan

# Apply the function and rename to lowercase to match the guide's pipeline
df['bathroom'] = df['Bathroom'].apply(extract_number)
df['balcony'] = df['Balcony'].apply(extract_number)
df['car_parking'] = df['Car Parking'].apply(extract_number)

# Drop the old columns
df.drop(columns=['Bathroom', 'Balcony', 'Car Parking'], inplace=True)

# Display the info to verify the new numeric columns
print(df[['bathroom', 'balcony', 'car_parking']].info())

<class 'pandas.DataFrame'>
Index: 177847 entries, 0 to 187530
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   bathroom     177087 non-null  float64
 1   balcony      130688 non-null  float64
 2   car_parking  81935 non-null   float64
dtypes: float64(3)
memory usage: 5.4 MB
None

In [15]:
df.info()  # Get information about the DataFrame, including data types and non-null counts

<class 'pandas.DataFrame'>
Index: 177847 entries, 0 to 187530
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Amount(in rupees)  177847 non-null  str
 1   Price (in rupees)  177847 non-null  float64
 2   location           177847 non-null  str
 3   Status             177252 non-null  str
 4   Floor              170898 non-null  str
 5   Transaction        177780 non-null  str
 6   Furnishing         175780 non-null  str
 7   facing             112111 non-null  str
 8   overlooking        102022 non-null  str
 9   Ownership          115922 non-null  str
 10  price_clean        177847 non-null  float64
 11  carpet_area_sqft   177722 non-null  float64
 12  bathroom           177087 non-null  float64
 13  balcony            130688 non-null  float64
 14  car_parking        81935 non-null   float64
dtypes: float64(6), str(9)
memory usage: 21.7 MB

In [16]:
# 1. Drop redundant and unused columns based on the pipeline requirements
cols_to_drop = ['Amount(in rupees)', 'Price (in rupees)', 'Status', 'overlooking']
df.drop(columns=cols_to_drop, inplace=True, errors='ignore')

# 2. Parse 'Floor' into numeric 'floor_num'
def parse_floor(x):
    if pd.isna(x):
        return np.nan
    x = str(x).lower().strip()
    if 'ground' in x: return 0.0
    if 'basement' in x: return -1.0
    match = re.search(r'\d+', x)
    return float(match.group()) if match else np.nan

df['floor_num'] = df['Floor'].apply(parse_floor)
df.drop(columns=['Floor'], inplace=True)

# 3. Group high-cardinality 'location' into top 50 + 'other'
top_50_locations = df['location'].value_counts().nlargest(50).index
df['location_grouped'] = df['location'].apply(lambda x: x if x in top_50_locations else 'other')
df.drop(columns=['location'], inplace=True)

# 4. Check final info
print(df.info())

<class 'pandas.DataFrame'>
Index: 177847 entries, 0 to 187530
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction       177780 non-null  str
 1   Furnishing        175780 non-null  str
 2   facing            112111 non-null  str
 3   Ownership         115922 non-null  str
 4   price_clean       177847 non-null  float64
 5   carpet_area_sqft  177722 non-null  float64
 6   bathroom          177087 non-null  float64
 7   balcony           130688 non-null  float64
 8   car_parking       81935 non-null   float64
 9   floor_num         170898 non-null  float64
 10  location_grouped  177847 non-null  str
dtypes: float64(6), str(5)
memory usage: 16.3 MB
None

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestRegressor

# 1. Remove outliers based on price per sqft (1st to 99th percentile)
df['price_per_sqft'] = df['price_clean'] / df['carpet_area_sqft']
q_low = df['price_per_sqft'].quantile(0.01)
q_high = df['price_per_sqft'].quantile(0.99)

# Filter the dataframe
df = df[(df['price_per_sqft'] >= q_low) & (df['price_per_sqft'] <= q_high)]

# Drop the temporary column
df.drop(columns=['price_per_sqft'], inplace=True)
print(f"Data shape after outlier removal: {df.shape}")

# 2. Define features and target
numeric_features = ["carpet_area_sqft", "floor_num", "bathroom", "balcony", "car_parking"]
categorical_features = ["location_grouped", "Furnishing", "Transaction", "Ownership", "facing"]

X = df[numeric_features + categorical_features]
y = df["price_clean"]

# 3. Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 4. Build the Pipeline
preprocessor = ColumnTransformer([
    ("num", Pipeline([
        ("impute", SimpleImputer(strategy="median")),
        ("scale", StandardScaler())
    ]), numeric_features),
    
    ("cat", Pipeline([
        ("impute", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]), categorical_features)
])

# Define the full model pipeline (using RandomForest as requested)
model = Pipeline([
    ("prep", preprocessor),
    ("reg", RandomForestRegressor(n_estimators=200, random_state=42))
])

# 5. Train the model (using log transformation for skewed target)
model.fit(X_train, np.log1p(y_train))
print("Model training completed successfully!")

Data shape after outlier removal: (174245, 11)
Model training completed successfully!

In [24]:
from sklearn.metrics import mean_absolute_error, root_mean_squared_error, r2_score
import numpy as np

# 1. Predict on the test set
# The predictions will be in log scale because we trained on log1p
log_predictions = model.predict(X_test)

# 2. Invert the log transformation to get the actual prices in Rupees
predictions = np.expm1(log_predictions)

# 3. Calculate evaluation metrics
mae = mean_absolute_error(y_test, predictions)
rmse = root_mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

# 4. Print the results formatted with commas for readability
print(f"Mean Absolute Error (MAE): {mae:,.2f} Rupees")
print(f"Root Mean Squared Error (RMSE): {rmse:,.2f} Rupees")
print(f"R-squared (R²): {r2:.4f}")

Mean Absolute Error (MAE): 911,735.45 Rupees
Root Mean Squared Error (RMSE): 3,092,456.22 Rupees
R-squared (R²): 0.9330

In [23]:
import joblib
import json
import sklearn

# 1. Export the full Pipeline (Preprocessing + Model)
joblib.dump(model, "house_price_RF.pkl")

# 2. Export the sorted list of allowed locations for the frontend dropdown
locations_list = sorted(df["location_grouped"].unique().tolist())
with open("locations.json", "w") as f:
    json.dump(locations_list, f)

# 3. Print the scikit-learn version to pin it in the backend later
print(f"Scikit-learn version used: {sklearn.__version__}")

Scikit-learn version used: 1.8.0

In [20]:
! pip install -r backendrequirements.txt

Requirement already satisfied: fastapi in D:\langGragh\.venv\Lib\site-packages (from -r backendrequirements.txt (line 1)) (0.136.0)
Requirement already satisfied: pydantic in D:\langGragh\.venv\Lib\site-packages (from -r backendrequirements.txt (line 3)) (2.13.2)
Requirement already satisfied: pydantic-settings in D:\langGragh\.venv\Lib\site-packages (from -r backendrequirements.txt (line 4)) (2.14.0)
Requirement already satisfied: pandas in D:\langGragh\.venv\Lib\site-packages (from -r backendrequirements.txt (line 5)) (3.0.2)
Requirement already satisfied: scikit-learn==1.8.0 in D:\langGragh\.venv\Lib\site-packages (from -r backendrequirements.txt (line 6)) (1.8.0)
Requirement already satisfied: joblib in D:\langGragh\.venv\Lib\site-packages (from -r backendrequirements.txt (line 7)) (1.5.3)
Requirement already satisfied: pytest in D:\langGragh\.venv\Lib\site-packages (from -r backendrequirements.txt (line 8)) (9.1.1)
Requirement already satisfied: httpx in D:\langGragh\.venv\Lib\site-packages (from -r backendrequirements.txt (line 9)) (0.28.1)
Requirement already satisfied: uvicorn[standard] in D:\langGragh\.venv\Lib\site-packages (from -r backendrequirements.txt (line 2)) (0.44.0)
Requirement already satisfied: numpy>=1.24.1 in D:\langGragh\.venv\Lib\site-packages (from scikit-learn==1.8.0->-r backendrequirements.txt (line 6)) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in D:\langGragh\.venv\Lib\site-packages (from scikit-learn==1.8.0->-r backendrequirements.txt (line 6)) (1.17.1)
Requirement already satisfied: threadpoolctl>=3.2.0 in D:\langGragh\.venv\Lib\site-packages (from scikit-learn==1.8.0->-r backendrequirements.txt (line 6)) (3.6.0)
Requirement already satisfied: starlette>=0.46.0 in D:\langGragh\.venv\Lib\site-packages (from fastapi->-r backendrequirements.txt (line 1)) (1.0.0)
Requirement already satisfied: typing-extensions>=4.8.0 in D:\langGragh\.venv\Lib\site-packages (from fastapi->-r backendrequirements.txt (line 1)) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in D:\langGragh\.venv\Lib\site-packages (from fastapi->-r backendrequirements.txt (line 1)) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in D:\langGragh\.venv\Lib\site-packages (from fastapi->-r backendrequirements.txt (line 1)) (0.0.4)
Requirement already satisfied: click>=7.0 in D:\langGragh\.venv\Lib\site-packages (from uvicorn[standard]->-r backendrequirements.txt (line 2)) (8.3.2)
Requirement already satisfied: h11>=0.8 in D:\langGragh\.venv\Lib\site-packages (from uvicorn[standard]->-r backendrequirements.txt (line 2)) (0.16.0)
Requirement already satisfied: colorama>=0.4 in D:\langGragh\.venv\Lib\site-packages (from uvicorn[standard]->-r backendrequirements.txt (line 2)) (0.4.6)
Requirement already satisfied: httptools>=0.6.3 in D:\langGragh\.venv\Lib\site-packages (from uvicorn[standard]->-r backendrequirements.txt (line 2)) (0.8.0)
Requirement already satisfied: python-dotenv>=0.13 in D:\langGragh\.venv\Lib\site-packages (from uvicorn[standard]->-r backendrequirements.txt (line 2)) (1.2.2)
Requirement already satisfied: pyyaml>=5.1 in D:\langGragh\.venv\Lib\site-packages (from uvicorn[standard]->-r backendrequirements.txt (line 2)) (6.0.3)
Requirement already satisfied: watchfiles>=0.20 in D:\langGragh\.venv\Lib\site-packages (from uvicorn[standard]->-r backendrequirements.txt (line 2)) (1.1.1)
Requirement already satisfied: websockets>=10.4 in D:\langGragh\.venv\Lib\site-packages (from uvicorn[standard]->-r backendrequirements.txt (line 2)) (17.0.1)
Requirement already satisfied: annotated-types>=0.6.0 in D:\langGragh\.venv\Lib\site-packages (from pydantic->-r backendrequirements.txt (line 3)) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.2 in D:\langGragh\.venv\Lib\site-packages (from pydantic->-r backendrequirements.txt (line 3)) (2.46.2)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\langGragh\.venv\Lib\site-packages (from pandas->-r backendrequirements.txt (line 5)) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\langGragh\.venv\Lib\site-packages (from pandas->-r backendrequirements.txt (line 5)) (2026.1)
Requirement already satisfied: iniconfig>=1.0.1 in D:\langGragh\.venv\Lib\site-packages (from pytest->-r backendrequirements.txt (line 8)) (2.3.0)
Requirement already satisfied: packaging>=22 in D:\langGragh\.venv\Lib\site-packages (from pytest->-r backendrequirements.txt (line 8)) (26.1)
Requirement already satisfied: pluggy<2,>=1.5 in D:\langGragh\.venv\Lib\site-packages (from pytest->-r backendrequirements.txt (line 8)) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in D:\langGragh\.venv\Lib\site-packages (from pytest->-r backendrequirements.txt (line 8)) (2.20.0)
Requirement already satisfied: anyio in D:\langGragh\.venv\Lib\site-packages (from httpx->-r backendrequirements.txt (line 9)) (4.13.0)
Requirement already satisfied: certifi in D:\langGragh\.venv\Lib\site-packages (from httpx->-r backendrequirements.txt (line 9)) (2026.2.25)
Requirement already satisfied: httpcore==1.* in D:\langGragh\.venv\Lib\site-packages (from httpx->-r backendrequirements.txt (line 9)) (1.0.9)
Requirement already satisfied: idna in D:\langGragh\.venv\Lib\site-packages (from httpx->-r backendrequirements.txt (line 9)) (3.11)
Requirement already satisfied: six>=1.5 in D:\langGragh\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->-r backendrequirements.txt (line 5)) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
import os
import joblib
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline

# 1. Build a pipeline combining the preprocessor and the model
# (Assuming 'preprocessor', 'X_train', 'y_train', 'X_test', 'y_test' are already defined in your notebook)
lr_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('model', LinearRegression())
])

# 2. Train the model using the training datasets
print("Training Linear Regression model...")
lr_pipeline.fit(X_train, y_train)

# 3. Evaluate the model's accuracy
train_score = lr_pipeline.score(X_train, y_train)
test_score = lr_pipeline.score(X_test, y_test)
print(f"Linear Regression Train Score: {train_score:.2f}")
print(f"Linear Regression Test Score: {test_score:.2f}")

# 4. Create the 'models' directory if it doesn't exist
os.makedirs('models', exist_ok=True)

# 5. Save the trained model to the directory
joblib.dump(lr_pipeline, 'models/house_price_lr.pkl')
print("Model saved successfully as models/house_price_lr.pkl")

Training Linear Regression model...
Linear Regression Train Score: 0.69
Linear Regression Test Score: 0.68
Model saved successfully as models/house_price_lr.pkl